### ISSUE TITLE
Learning WRM - Gaussian Naive Bayes

### ISSUE THREAD

**Issue by becxer** [socc-io/Hawki#3]
1st Target Date. 16.08.14

**Comment by oh4851** [comment]
**관련자료**
- [Naive Bayesian Classification 소개(조대협님 블로그)](http://bcho.tistory.com/1010)
- [Naive Bayes : Gaussian example](https://www.youtube.com/watch?v=r1in0YNetG8)

**Comment by oh4851** [comment]
- sklearn.gaussian nb can't get float number
  - 1): first use with, sklearn.BaysianRidge + float number
  - 2): second use with, sklearn.GaussianNB + int number (mapping area number)
